FROM nvcr.io/nvidia/tritonserver:23.10-py3

WORKDIR /models

# Copy ONNX model repository configurations and models
COPY triton_model_repository/ /models/

EXPOSE 8000 8001 8002

CMD ["tritonserver", "--model-repository=/models", "--strict-model-config=false"]
